name: unit-tests
run-name: ${{github.actor}} trigged the unit tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
      - run: npm install
      - run: npm run test
